### ISSUE TITLE
.accdb support?

### ISSUE THREAD

**Issue by himselfv** [himselfv/jet-tool#7]
**[Original report](https://bitbucket.org/himselfv/jet-tool/issue/7) by Anonymous.**

----------------------------------------

What is my best option to get the functionality of jet-tool when supporting newer database formats, such as .accdb?
I know that Microsoft converted the JET engine into something they renamed as the ACE engine to support the new file format - hence my question about the future of jet-tool or a successor to it.

Thanks, Paul.W -at- IndustrialControl.co.nz

**Comment by rpresser** [comment]
Happens even if you rename the .accdb back to .mdb :(

**Comment by himselfv** [comment]
@rpresser Does this happen even on latest versions? https://github.com/himselfv/jet-tool/releases/tag/0.6b (Github messed up the "latest" release for some reason so some people might have been downloading 0.5)
Have you read this? -- https://github.com/himselfv/jet-tool/blob/master/docs/Providers.md

**Comment by rpresser** [comment]
To be perfectly honest, I have no idea. I haven't had to deal with any
accdb files since I posted here and none appear likely to show up for me in
the near future either.
